include:
- local: ci/include.yml

stages:
  - test
  - docker
  - ubuntu
  - others

# RELEASE_TAG should be updated to an already released version from time to time.
variables:
  RELEASE_TAG: 'v2.0.3'
  BASE_REGISTRY: ${CI_REGISTRY_IMAGE}

# Templates
.test-settings:
  extends:
    - .rule-include-development-branches
    - .gitlab-runner-tag

.release-settings:
  extends:
    - .before-script-docker-login
    - .gitlab-runner-tag
    - .rule-include-default-branch-or-tags
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        BUILD_TAG: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        BUILD_TAG: latest
    - if: $BUILD_TAG

# Test stage
Shell Linter:
  stage: test
  extends: .test-settings
  image: ${CI_REGISTRY_IMAGE}/test:latest
  script: lint.sh shell

Build all images:
  stage: test
  extends: .test-settings
  image: ${CI_REGISTRY_IMAGE}/docker:latest
  script: make all
  timeout: 3h

Gitleaks:
  extends: .gitleaks

Shell Unit Tests:
  extends: .shell-unit-tests

Check BASE_DOCKER_TAG:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/ubuntu:${RELEASE_TAG}
  variables:
    FILE: 'ci/images.yml'
    VARIABLE: 'BASE_DOCKER_TAG'
  extends:
    - .fail-if-variable-value-is-not-found-in-file
  rules:
    - if: $CI_COMMIT_TAG != null
      variables:
        VALUE: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        VALUE: 'latest'

# Build stage
# The docker image is built using an already published docker image (RELEASE_TAG)
# to resolve the circular dependency. All other images are built using the docker image
# that has just been created (BUILD_TAG).
Build docker:
  stage: docker
  image: ${CI_REGISTRY_IMAGE}/docker:${RELEASE_TAG}
  extends: .release-settings
  script: make release IMAGE=docker

Build ubuntu:
  stage: ubuntu
  image: ${CI_REGISTRY_IMAGE}/docker:${BUILD_TAG}
  extends: .release-settings
  script: make release IMAGE=ubuntu

Build test:
  stage: others
  image: ${CI_REGISTRY_IMAGE}/docker:${BUILD_TAG}
  extends: .release-settings
  script: make release IMAGE=test

Build yocto:
  stage: others
  image: ${CI_REGISTRY_IMAGE}/docker:${BUILD_TAG}
  extends: .release-settings
  script: make release IMAGE=yocto
